services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '4.0'
    volumes:
      - .:/app
    restart: always
    tty: true
